
["General Mobs"]
	"Mob View Range" = 128.0

[Creepers]
	"Attempt Breach" = true
	"Creeper Breach Timer" = 120.0

[Spiders]
	"Can Shoot Web" = true
	"Shoot Web Interval" = 180.0

[Endermen]
	"Can Teleport Player" = true
	"Teleport Player Interval" = 120.0

[Ravagers]
	"Can Break Blocks" = true
	"Ravager Charge Interval" = 120.0
	"Ravager Break Block Hardness" = 2.0

